import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./NavBar/Navbar";
import Footer from "./Footer/Footer";
import Providers from './provider/Providers'
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Providers className=" w-full ">
          <Toaster
          position="top-center"
          reverseOrder={false}
          />
          {children}</Providers>
        <Footer />
      </body>
    </html>
   

  
  );
}
